---
title: "A Response to Class Divide"
author: "Adam Dennett"
date: 2026-07-29
draft: true
---

## Introduction

On the 21st July 2026, I gave a [public lecture](https://www.youtube.com/watch?v=Qaqm8vkppI0) at BHASVIC in Brighton. The talk was designed to present the findings of a [new report](https://adamdennett.github.io/school_attainment_tool/index.html) I have been working on for the last 6-months or so where I have tried to delve into the depths of the drivers of secondary school attainment in England and to allow interested members of the public and local politicians to come along and listen and ask questions. 

The work I have been doing was motivated by my experiences of living in Brighton and Hove over the last 2 years and the changes the council have been making to the way that secondary school places are allocated in the city. 

The changes proposed in 2024 and 2025 mean that for children like my daughter, there is now a non-zero chance that she will not be able to attend either of the two secondary schools near to where she lives. 
